export const SEED_STOCKS = [
  { symbol: "RELIANCE", companyName: "Reliance Industries", sector: "Energy", currentPrice: 2845, changePercent: 2.4, marketCap: 19_00000 },
  { symbol: "TCS", companyName: "Tata Consultancy Services", sector: "Technology", currentPrice: 4120, changePercent: 1.2, marketCap: 15_00000 },
  { symbol: "INFY", companyName: "Infosys", sector: "Technology", currentPrice: 1785, changePercent: -0.8, marketCap: 7_50000 },
  { symbol: "HDFCBANK", companyName: "HDFC Bank", sector: "Banking", currentPrice: 1920, changePercent: 3.1, marketCap: 12_00000 },
  { symbol: "ICICIBANK", companyName: "ICICI Bank", sector: "Banking", currentPrice: 1180, changePercent: 1.5, marketCap: 8_00000 },
  { symbol: "SBIN", companyName: "State Bank of India", sector: "Banking", currentPrice: 820, changePercent: 0.9, marketCap: 7_00000 },
  { symbol: "BHARTIARTL", companyName: "Bharti Airtel", sector: "Telecom", currentPrice: 1580, changePercent: 2.1, marketCap: 9_00000 },
  { symbol: "ITC", companyName: "ITC Limited", sector: "FMCG", currentPrice: 465, changePercent: -0.3, marketCap: 5_80000 },
  { symbol: "HINDUNILVR", companyName: "Hindustan Unilever", sector: "FMCG", currentPrice: 2380, changePercent: 0.6, marketCap: 5_60000 },
  { symbol: "LT", companyName: "Larsen & Toubro", sector: "Infrastructure", currentPrice: 3650, changePercent: 1.8, marketCap: 5_00000 },
  { symbol: "AXISBANK", companyName: "Axis Bank", sector: "Banking", currentPrice: 1120, changePercent: -1.2, marketCap: 4_50000 },
  { symbol: "KOTAKBANK", companyName: "Kotak Mahindra Bank", sector: "Banking", currentPrice: 1780, changePercent: 0.4, marketCap: 4_20000 },
  { symbol: "WIPRO", companyName: "Wipro", sector: "Technology", currentPrice: 520, changePercent: -1.5, marketCap: 2_80000 },
  { symbol: "MARUTI", companyName: "Maruti Suzuki", sector: "Automobile", currentPrice: 12500, changePercent: 2.8, marketCap: 4_00000 },
  { symbol: "TATAMOTORS", companyName: "Tata Motors", sector: "Automobile", currentPrice: 980, changePercent: 3.5, marketCap: 3_50000 },
  { symbol: "SUNPHARMA", companyName: "Sun Pharmaceutical", sector: "Pharma", currentPrice: 1680, changePercent: 1.1, marketCap: 4_00000 },
  { symbol: "ONGC", companyName: "Oil & Natural Gas Corp", sector: "Energy", currentPrice: 285, changePercent: -0.7, marketCap: 3_60000 },
  { symbol: "NTPC", companyName: "NTPC Limited", sector: "Energy", currentPrice: 380, changePercent: 0.8, marketCap: 3_70000 },
  { symbol: "POWERGRID", companyName: "Power Grid Corp", sector: "Energy", currentPrice: 320, changePercent: 0.5, marketCap: 3_00000 },
  { symbol: "ASIANPAINT", companyName: "Asian Paints", sector: "FMCG", currentPrice: 2980, changePercent: -0.9, marketCap: 2_90000 },
  { symbol: "BAJFINANCE", companyName: "Bajaj Finance", sector: "Finance", currentPrice: 7200, changePercent: 1.6, marketCap: 4_50000 },
  { symbol: "TITAN", companyName: "Titan Company", sector: "Consumer", currentPrice: 3450, changePercent: 2.2, marketCap: 3_10000 },
  { symbol: "ADANIENT", companyName: "Adani Enterprises", sector: "Conglomerate", currentPrice: 3100, changePercent: -2.1, marketCap: 3_50000 },
  { symbol: "HCLTECH", companyName: "HCL Technologies", sector: "Technology", currentPrice: 1680, changePercent: 1.0, marketCap: 4_60000 },
];
